// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHy1BkVfGTtqSIpo1sG3PJoeqXsuYnpyY',
    appId: '1:1037868001310:web:6b46840301c1c944af660f',
    messagingSenderId: '1037868001310',
    projectId: 'life-hero-app-118e4',
    authDomain: 'life-hero-app-118e4.firebaseapp.com',
    storageBucket: 'life-hero-app-118e4.firebasestorage.app',
    measurementId: 'G-B3ZYWHV4MG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDblK-gGPnb5ENAFeqmWg14eOLM_njCvrY',
    appId: '1:1037868001310:android:a91a0bc49a7b72b0af660f',
    messagingSenderId: '1037868001310',
    projectId: 'life-hero-app-118e4',
    storageBucket: 'life-hero-app-118e4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrFF0mgJbmohgUuTjEr2fVIWYpKLXcIsE',
    appId: '1:1037868001310:ios:e9c9cd784a6f3865af660f',
    messagingSenderId: '1037868001310',
    projectId: 'life-hero-app-118e4',
    storageBucket: 'life-hero-app-118e4.firebasestorage.app',
    iosBundleId: 'com.example.lifeHeroApp',
  );
}
